# Generated by Django 5.1.6 on 2025-03-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='food_images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('calories_per_10g', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
