# Generated by Django 5.1.6 on 2025-03-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('shop_owner', 'Shop Owner')], default='customer', max_length=20),
        ),
    ]
